Repository gluster/redant, pull requests merged in 2021-05, with the labels that each got.

#238 Added the total time information in the result file
  core/redant_main.py
  core/result_handler.py
Labels: Simple Fix, enhancement

#242 User credentials are removed from config file
  config/CONFIG_README.md
  config/config.yml
Labels: enhancement

#241 Added option for storing results in excel sheet
  core/redant_main.py
  core/result_handler.py
  requirements.txt
Labels: enhancement

#232 Check is added for existence and accessibility of config_file
  core/parsing/test_parser.py
  core/redant_main.py
Labels: bug

#247 Added information about the flags
  README.md
Labels: documentation

#252 Adding async capabilities in rexe.
  common/rexe.py
Labels: Critical, Urgent

#254 Basic io functions are added
  common/ops/support_ops/io_ops.py
Labels: enhancement

#256 Datastructure for volume level data.
  common/ops/gluster_ops/volume_ops.py
  tests/parent_test.py
Labels: Critical, Urgent, enhancement

#243 Added message to handle connection failure
  common/rexe.py
  core/environ.py
  tests/functional/glusterd/test_glusterd_start_stop.py
Labels: Simple Fix, Urgent

#259 Modified abstract ops multinode
  common/ops/abstract_ops.py
Labels: bug

#273 Removed success messages from gluster ops
  common/ops/gluster_ops/gluster_ops.py
Labels: enhancement

#266 Dispersed Volume and Distributed-Dispersed Volume creation is added
  common/ops/gluster_ops/volume_ops.py
  config/config.yml
  tests/example/sample_component/test_vol_creation.py
Labels: enhancement

#264 Readme, design decisions and thought process
  README.md
  docs/BPIndex.md
  docs/RP/Common/Index.md
  docs/RP/Common/logging.md
  docs/RP/Common/mixin.md
  docs/RP/Core/Index.md
  docs/RP/Core/result_handler.md
  docs/RP/HLD.md
  docs/RP/Test/Index.md
  docs/RP/WIRA.md
  docs/RPIndex.md
Labels: documentation

#274 Converting the TC as nonDisruptive.
  tests/example/sample_component/test_sample.py
Labels: Simple Fix

#276 [Lint Fix] Fixed some flake issues.
  .github/workflows/linting.yml
  .pylintrc
  MAINTAINERS
  common/mixin.py
  common/ops/abstract_ops.py
  common/ops/gluster_ops/gluster_ops.py
  common/ops/gluster_ops/peer_ops.py
  common/ops/gluster_ops/volume_ops.py
  common/ops/support_ops/io_ops.py
  common/relog.py
  common/rexe.py
  core/environ.py
  core/parsing/test_parser.py
  core/redant_main.py
  core/result_handler.py
  core/runner_thread.py
  core/test_runner.py
  tests/example/sample_component/test_sample.py
  tests/parent_test.py
Labels: Simple Fix

#285 Modified docstrings in all the ops
  common/ops/gluster_ops/gluster_ops.py
  common/ops/gluster_ops/volume_ops.py
  common/ops/support_ops/io_ops.py
Labels: documentation

#211 Flag for skipping the test is added
  config/CONFIG_README.md
  config/config.yml
  core/parsing/params_handler.py
  core/redant_main.py
  core/test_list_builder.py
  core/test_runner.py
Labels: enhancement

#289 Changed parent test to abstract test
  README.md
  docs/RP/HLD.md
  tests/README.md
  tests/abstract_test.py
  tests/example/sample_component/test_sample.py
  tests/example/sample_component/test_vol_creation.py
  tests/functional/glusterd/test_glusterd_start_stop.py
Labels: enhancement

#288 Lint script modified
  tools/linting.sh
Labels: enhancement

#293 [Test] Test glusterd set reset reserve limit
  common/ops/gluster_ops/volume_ops.py
  tests/functional/glusterd/test_glusterd_set_reset_reserve_limit.py
Labels: Simple Fix

#296 [Doc] Test case migration doc.
  README.md
  docs/BP/migratingTC.md
  docs/BPIndex.md
Labels: documentation

#173 Added brick ops
  .pylintrc
  common/mixin.py
  common/ops/gluster_ops/brick_ops.py
  core/redant_main.py
  tests/functional/glusterd/test_add_remove_brick.py
Labels: enhancement

#304 Added test_default_log_level_of_cli
  tests/functional/glusterd/test_default_log_level_of_cli.py
Labels: enhancement

#291 IO ops on mountpoint is added
  common/ops/support_ops/io_ops.py
  common/rexe.py
  config/config.yml
  tests/functional/glusterd/test_io.py
Labels: enhancement

#307 Added test_default_max_bricks_per_process
  tests/functional/glusterd/test_default_max_bricks_per_process.py
Labels: enhancement

#312 [Test] test_glusterd_quorum_command migration
  tests/functional/glusterd/test_glusterd_quorum_command.py
Labels: testMigration

#322 Changed the execute_command call in is_glusterd_running
  common/ops/gluster_ops/gluster_ops.py
Labels: bug

#318 Added test_enable_storage_reserve_volume
  tests/functional/glusterd/test_enable_storage_reserve_volume.py
Labels: testMigration

#324 [Core][Common] Log dir creation and test list
  common/relog.py
  core/redant_main.py
  core/test_list_builder.py
  core/test_runner.py
Labels: Common, Core, Critical, Urgent, enhancement

#271 PeerOps Modified
  .github/workflows/linting.yml
  common/ops/gluster_ops/peer_ops.py
  core/environ.py
  tools/linting.sh
Labels: bug, enhancement

#306 [Common] cleands data structure
  common/mixin.py
  common/ops/gluster_ops/volume_ops.py
Labels: Critical, documentation, enhancement

#329 Fixing the typo which leads to test failure
  common/ops/gluster_ops/volume_ops.py
Labels: Common, Urgent, bug

#325 Added test_op_version
  tests/functional/glusterd/test_op_version.py
Labels: testMigration

#332 Fixed wait_for_glusterd issues
  common/ops/gluster_ops/gluster_ops.py
Labels: bug

#341 execute_io_cmd is removed
  common/ops/support_ops/io_ops.py
  tests/abstract_test.py
  tests/example/sample_component/test_sample.py
  tests/functional/glusterd/test_io.py
Labels: enhancement

#343 Migrated test_lower_gluster_op_version
  tests/functional/glusterd/test_lower_gluster_op_version.py
Labels: testMigration

#336 Migration of test_glusterd_logs_when_peer_detach
  tests/functional/glusterd/test_glusterd_logs_when_peer_detach.py
Labels: testMigration

#337 Migration of test_glusterd_selinux
  tests/functional/glusterd/test_glusterd_selinux.py
Labels: testMigration

#344 Fixed test_add_remove_brick issue
  tests/functional/glusterd/test_add_remove_brick.py
Labels: bug

#346 Migrated test_setting_volume_level_option_to_cluster
  common/ops/gluster_ops/gluster_ops.py
  tests/functional/glusterd/test_setting_volume_level_option_to_cluster.py
Labels: testMigration

#330 Added test_glusterd_friend_updates_on_node_rejoin
  common/ops/gluster_ops/gluster_ops.py
  tests/functional/glusterd/test_change_reserve_limit_to_wrong_values.py
  tests/functional/glusterd/test_default_log_level_of_cli.py
  tests/functional/glusterd/test_default_max_bricks_per_process.py
  tests/functional/glusterd/test_enable_storage_reserve_volume.py
  tests/functional/glusterd/test_glusterd_friend_updates_on_node_rejoin.py
  tests/functional/glusterd/test_glusterd_quorum_command.py
  tests/functional/glusterd/test_glusterd_set_reset_reserve_limit.py
  tests/functional/glusterd/test_op_version.py
Labels: testMigration

#333 [Core][Common][Tests] Test execution re-imagined
  .pylintrc
  common/mixin.py
  common/ops/gluster_ops/brick_ops.py
  common/ops/gluster_ops/volume_ops.py
  core/environ.py
  core/redant_main.py
  core/runner_thread.py
  core/test_list_builder.py
  core/test_runner.py
  tests/__init__.py
  tests/d_parent_test.py
  tests/example/sample_component/test_sample.py
  tests/example/sample_component/test_vol_creation.py
  tests/functional/glusterd/test_add_remove_brick.py
  tests/functional/glusterd/test_change_reserve_limit_to_wrong_values.py
  tests/functional/glusterd/test_default_log_level_of_cli.py
  tests/functional/glusterd/test_default_max_bricks_per_process.py
  tests/functional/glusterd/test_enable_storage_reserve_volume.py
  tests/functional/glusterd/test_glusterd_friend_updates_on_node_rejoin.py
  tests/functional/glusterd/test_glusterd_logs_when_peer_detach.py
  tests/functional/glusterd/test_glusterd_quorum_command.py
  tests/functional/glusterd/test_glusterd_selinux.py
  tests/functional/glusterd/test_glusterd_set_reset_reserve_limit.py
  tests/functional/glusterd/test_glusterd_start_stop.py
  tests/functional/glusterd/test_io.py
  tests/functional/glusterd/test_lower_gluster_op_version.py
  tests/functional/glusterd/test_op_version.py
  tests/functional/glusterd/test_setting_volume_level_option_to_cluster.py
  tests/lazy_parent_test.py
  tests/nd_parent_test.py
  tests/vol_create_test.py
  tests/vol_destroy_test.py
Labels: Common, Core, Critical, Test, bug, documentation, enhancement

#361 [Tests] Moved tests from glusterd to example
  tests/example/sample_component/test_add_remove_brick.py
  tests/example/sample_component/test_io.py
Labels: Simple Fix, Test

#372 [Tools] Migration Script
  tools/migrate_tc.py
Labels: enhancement

#369 Migrated test_updates_in_options_file_on_quorum_changes.py
  tests/functional/glusterd/test_updates_in_options_file_on_quorum_changes.py
Labels: testMigration

#350 Migrated test_ops_when_one_node_is_down
  tests/functional/glusterd/test_ops_when_one_node_is_down.py
Labels: testMigration

#376 Deleted test_add_remove_brick and test_io
  tests/functional/glusterd/test_add_remove_brick.py
  tests/functional/glusterd/test_io.py
Labels: Simple Fix

#338 Migration of test_gluster_volume_status_xml_dump
  tests/functional/glusterd/test_gluster_volume_status_xml_dump.py
Labels: testMigration

#385 Profiles operation are added
  common/mixin.py
  common/ops/gluster_ops/profile_ops.py
  tests/example/sample_component/test_profile_ops.py
Labels: enhancement

#383 Migrated test_probe_hostname and added form_brick_cmd in brick ops
  common/mixin.py
  common/ops/gluster_ops/brick_ops.py
  common/ops/gluster_ops/peer_ops.py
  common/ops/gluster_ops/volume_ops.py
  core/environ.py
  tests/functional/glusterd/test_probe_hostname.py
Labels: Common, bug, testMigration

#384 [Tools] Test conversion script.
  .github/workflows/linting.yml
  .pylintrc
  docs/BP/migratingTC.md
  docs/RP/Tools/Index.md
  docs/RP/Tools/glusto_redant_parser.md
  docs/RP/Tools/migrate_tc.md
  docs/RPIndex.md
  tools/glusto_redant_parser.py
Labels: documentation, enhancement

#391 [Doc] Adding a skeletal doc structure.
  README.md
  docs/BP/Ops/glusterd_ops.md
  docs/BP/Ops/opsIndex.md
  docs/BP/Ops/peer_ops.md
  docs/BP/Ops/profile_ops.md
  docs/BP/Ops/volume_ops.md
  docs/BP/Tools/migratingTC.md
  docs/BPIndex.md
Labels: documentation

#397 Migrated test_profile_start_with_quorum_not_met
  common/ops/gluster_ops/peer_ops.py
  tests/functional/glusterd/test_profile_start_with_quorum_not_met.py
Labels: Common, testMigration

#402 [Test] Migration of test_volume_status_xml
  tests/functional/glusterd/test_volume_status_xml.py
Labels: testMigration

#405 [Doc] Added doc about brick ops
  common/ops/gluster_ops/brick_ops.py
  docs/BP/Ops/brick_ops.md
  docs/BP/Ops/opsIndex.md
Labels: documentation

#415 Added doc for peer ops
  common/ops/gluster_ops/peer_ops.py
  docs/BP/Ops/opsIndex.md
  docs/BP/Ops/peer_ops.md
Labels: documentation

#407 [Doc] Adding documentation for Rexe functions
  docs/BP/Ops/opsIndex.md
  docs/BP/Ops/rexe.md
Labels: documentation

#421 Adding excep flag to bypass exception
  common/ops/abstract_ops.py
  common/ops/gluster_ops/volume_ops.py
Labels: enhancement

#422 [Core][Common][Test][Tools] File_dir_script
  common/mixin.py
  common/ops/support_ops/io_ops.py
  common/rexe.py
  core/environ.py
  tests/d_parent_test.py
  tests/lazy_parent_test.py
  tests/nd_parent_test.py
  tools/file_dir_ops.py
Labels: Common, Core, Test, enhancement

#424 [Core] Logger invocation correction
  core/environ.py
Labels: bug

#425 Added the summary stats in results
  core/result_handler.py
  core/test_list_builder.py
  core/test_runner.py
Labels: Core, Simple Fix, enhancement

#426 Cleanup of volumes creates in test case in disruptive tc
  core/environ.py
  tests/d_parent_test.py
Labels: bug

#406 Added documentation for BP volume ops
  docs/BP/Ops/volume_ops.md
Labels: documentation

#428 [Core][Common][Test] Sanitize and cleanup
  common/ops/gluster_ops/brick_ops.py
  common/ops/gluster_ops/volume_ops.py
  core/environ.py
  tests/d_parent_test.py
  tests/functional/glusterd/test_enable_storage_reserve_volume.py
  tests/lazy_parent_test.py
  tests/nd_parent_test.py
  tests/vol_destroy_test.py
Labels: Common, Core, Test, Urgent, bug, enhancement

#432 [Core] Check for generic test
  core/test_runner.py
Labels: bug

#442 [Test] Adding vol option cleanup in d_parent_test
  core/environ.py
  tests/d_parent_test.py
  tests/nd_parent_test.py
Labels: Test, enhancement

#444 Peer probe success checks for peer state as 3
  common/ops/gluster_ops/peer_ops.py
Labels: bug

#310 Added test_default_ping_timer_and_epoll_thread_count
  tests/functional/glusterd/test_default_ping_timer_and_epoll_thread_count.py
Labels: enhancement, testMigration

#438 Migrated test_validate_auth_allow_and_auth_reject
  tests/functional/glusterd/test_validate_auth_allow_and_auth_reject.py
Labels: testMigration

#450 Modified the test_default_piing_timer_and_epoll_thread_count
  tests/functional/glusterd/test_default_ping_timer_and_epoll_thread_count.py
Labels: testMigration

#454 [Core][Test] d_parent_handling and mount ds fix
  core/environ.py
  tests/d_parent_test.py
Labels: Core, Test, Urgent, bug

#413 Migrated test_add_brick_when_quorum_not_met
  common/ops/gluster_ops/brick_ops.py
  core/environ.py
  docs/BP/Ops/brick_ops.md
  tests/functional/glusterd/test_add_brick_when_quorum_not_met.py
Labels: Common, testMigration

#404 [Test] Migrating test_readonly_option_on_volume
  common/ops/support_ops/io_ops.py
  tests/functional/glusterd/test_readonly_option_on_volume.py
Labels: testMigration

#460 Changes in test_add_brick_when_quorum_not_met
  tests/functional/glusterd/test_add_brick_when_quorum_not_met.py
Labels: testMigration

#427 Added test_remove_brick_when_quorum_not_met
  tests/functional/glusterd/test_remove_brick_when_quorum_not_met.py
Labels: testMigration

#464 terminate funtionalities are added in try except
  tests/functional/glusterd/test_brick_port_after_stop_glusterd_modify_volume.py
Labels: Urgent, bug

#472 Mount cleanup corner case handling
  common/ops/gluster_ops/volume_ops.py
  common/ops/support_ops/io_ops.py
Labels: bug

#469 ret_msg value is updated
  tests/functional/glusterd/test_glusterd_selinux.py
Labels: Simple Fix, Urgent, bug

#471 Change path of glusterd.vol in the test
  tests/functional/glusterd/test_default_ping_timer_and_epoll_thread_count.py
Labels: Simple Fix, bug

#474 Added the function get_all_bricks
  common/ops/gluster_ops/brick_ops.py
Labels: Common

#482 Migration of test_peer_probe and changes to cleanup_volume
  common/ops/gluster_ops/volume_ops.py
  core/environ.py
  tests/d_parent_test.py
  tests/functional/glusterd/test_peer_probe.py
  tests/vol_destroy_test.py
Labels: testMigration

#456 Added check_core_file_exists and test_probe_glusterd
  .pylintrc
  common/ops/support_ops/io_ops.py
  tests/functional/glusterd/test_probe_glusterd.py
Labels: Common, testMigration

#484 [Test] Fixing spurious failure in TC.
  tests/functional/glusterd/test_gluster_volume_status_xml_dump.py
Labels: bug

#476 Added the functions in brick ops
  common/ops/gluster_ops/brick_ops.py
Labels: Common

#489 [FRMV] Machine ops and related test
  common/mixin.py
  common/ops/gluster_ops/peer_ops.py
  common/ops/support_ops/machine_ops.py
  common/rexe.py
  docs/BP/Ops/README.md
  docs/BP/Ops/machine_ops.md
  docs/BP/Ops/rexe.md
  tests/d_parent_test.py
  tests/example/sample_component/test_machine_ops.py
  tests/nd_parent_test.py
Labels: Common, Test, documentation, enhancement

#490 Added a test case to check the get_online_bricks_list and
  tests/example/sample_component/test_brick_ops.py
Labels: enhancement

#495 Modifying Maintainers list on actual contributions.
  MAINTAINERS
Labels: documentation

#498 Brick ops enhancement
  common/ops/gluster_ops/brick_ops.py
  common/ops/gluster_ops/gluster_ops.py
  docs/BP/Ops/brick_ops.md
  tests/example/sample_component/test_brick_ops.py
Labels: Common, documentation, enhancement

#493 [Common] Adding functions to IO Ops
  common/ops/support_ops/io_ops.py
  docs/BP/Ops/README.md
  docs/BP/Ops/io_ops.md
  tests/example/sample_component/test_io.py
Labels: documentation, enhancement

#507 [Common][Test] Migrated a get-state test
  common/ops/gluster_ops/brick_ops.py
  common/ops/gluster_ops/gluster_ops.py
  common/ops/gluster_ops/volume_ops.py
  docs/BP/Ops/README.md
  docs/BP/Ops/glusterd_ops.md
  docs/BP/Ops/volume_ops.md
  requirements.txt
  tests/example/sample_component/test_glusterd_ops.py
  tests/functional/glusterd/test_getstate_shows_correct_brick_status_when_brick_killed.py
Labels: enhancement, testMigration

#512 [Test] Migrating test_rebalance_hang
  tests/functional/glusterd/test_rebalance_hang.py
Labels: testMigration

#513 [Test] Migration of a brick test.
  tests/functional/glusterd/test_brick_status_when_quorum_not_met.py
Labels: testMigration

#522 [Test] migration of a test case in rebalance
  common/ops/gluster_ops/peer_ops.py
  common/ops/gluster_ops/rebalance_ops.py
  tests/d_parent_test.py
  tests/functional/glusterd/test_rebalance_when_quorum_not_met.py
Labels: Common, bug, testMigration

#524 [Doc] Adding rebalance ops doc
  common/ops/gluster_ops/rebalance_ops.py
  docs/BP/Ops/README.md
  docs/BP/Ops/rebalance_ops.md
Labels: documentation, enhancement

#440 Migrating test_concurrent_set.py from glusto to redant
  tests/functional/glusterd/test_concurrent_set.py
Labels: testMigration

#519 [Test][Common][Doc] Brick remove enhancement
  common/ops/gluster_ops/brick_ops.py
  common/ops/support_ops/io_ops.py
  docs/BP/Ops/brick_ops.md
  docs/BP/Ops/io_ops.md
  tests/example/sample_component/test_add_remove_brick.py
  tests/functional/glusterd/test_rebalance_spurious.py
  tests/functional/glusterd/test_remove_brick_when_quorum_not_met.py
Labels: Common, documentation, enhancement, testMigration

#530 Migration of test_rebalance_new_node.py from glusto to redant
  tests/functional/glusterd/test_rebalance_new_node.py
Labels: testMigration

#531 Migrated test_gluster_does_not_do_posix_lock_when_multiple_client
  common/ops/abstract_ops.py
  tests/functional/glusterd/test_gluster_does_not_do_posix_lock_when_multiple_client.py
Labels: testMigration

#533 Migrated test_glusterd_restart_quorum_not_met
  tests/functional/glusterd/test_glusterd_restart_quorum_not_met.py
Labels: testMigration

#532 [Common] Brick addition and listing
  common/ops/gluster_ops/brick_ops.py
  core/environ.py
  docs/BP/Ops/brick_ops.md
  tests/d_parent_test.py
  tests/example/sample_component/test_brick_ops.py
  tests/functional/glusterd/test_add_brick_when_quorum_not_met.py
  tests/functional/glusterd/test_rebalance_new_node.py
Labels: Common, Critical, documentation, enhancement

#538 Migration of test_xml_dump_of_gluster_volume_status_during_rebalance
  common/ops/gluster_ops/volume_ops.py
  tests/functional/glusterd/test_xml_dump_of_gluster_volume_status_during_rebalance.py
Labels: testMigration

#540 Migration of test_change_reserve_limit.py
  tests/functional/glusterd/test_change_reserve_limit.py
  tests/nd_parent_test.py
Labels: Common, testMigration
