Repository gluster/redant, pull requests merged in 2021-09, with the labels that each got.

#993 Migrated TC test_self_heal.py
  tests/functional/afr/heal/test_self_heal.py
Labels: testMigration

#1017 Migrate TC tests/functional/dht/test_rebalance_multiple_expansions.py
  tests/functional/dht/test_rebalance_multiple_expansions.py
Labels: testMigration

#1016 Migrate TC tests/functional/snapshot/test_restore_online_vol.py
  tests/functional/snapshot/test_restore_online_vol.py
Labels: testMigration

#1032 Migrated TC tests/functional/disperse/test_ec_all_healtypes.py
  tests/functional/disperse/test_ec_all_healtypes.py
Labels: testMigration

#1033 Migrate TC tests/functional/disperse/test_ec_basic.py
  tests/functional/disperse/test_ec_basic.py
Labels: testMigration

#1031 Migrate TC tests/functional/disperse/test_disperse_eager_lock.py
  tests/functional/disperse/test_disperse_eager_lock.py
Labels: testMigration

#1030 Migrate Test tests/functional/fuse_subdir/test_auth_allow_fqdn.py
  common/ops/gluster_ops/mount_ops.py
  tests/functional/fuse_subdir/test_auth_allow_fqdn.py
Labels: testMigration

#1044 Migrated Tc tests/functional/fuse_subdir/test_auth_allow_ip_fqdn.py
  tests/functional/fuse_subdir/test_auth_allow_ip_fqdn.py
Labels: testMigration

#1050 Migrate TC tests/functional/disperse/test_ec_add_brick.py
  tests/functional/disperse/test_ec_add_brick.py
Labels: testMigration

#1052 Migrated TC test_ec_check_lock_granted_to_2_different_client.py
  core/environ.py
  tests/functional/disperse/test_ec_check_lock_granted_to_2_different_client.py
  tools/file_lock.py
Labels: testMigration

#1054 Fix: Updated object name
  core/environ.py
  tests/d_parent_test.py
Labels: Critical

#1059 [Core] Fix handling of wrong path for a TC
  core/test_list_builder.py
Labels: bug, Core

#1066 Migrated TC test_ec_io_hang_clientside_heal.py
  tests/functional/disperse/test_ec_io_hang_clientside_heal.py
Labels: testMigration

#1065 Migrated TC test_ec_io_hang_serverside_heal.py
  tests/functional/disperse/test_ec_io_hang_serverside_heal.py
Labels: testMigration

#1067 Migrated TC test_ec_eager_lock_functional_validation.py
  tests/functional/disperse/test_ec_eager_lock_functional_validation.py
Labels: testMigration

#1071 Migrated TC test_ec_data_delete.py
  tests/functional/disperse/test_ec_data_delete.py
Labels: testMigration

#1072 Migrated TC test_ec_data_intergrity.py
  tests/functional/disperse/test_ec_data_intergrity.py
Labels: testMigration

#1080 Migrate TC tests/functional/disperse/test_ec_fops.py
  tests/functional/disperse/test_ec_fops.py
Labels: testMigration

#1079 Migrate TC tests/functional/disperse/test_ec_fops_brickdown.py
  tests/functional/disperse/test_ec_fops_brickdown.py
Labels: testMigration

#1084 Migrate TC test_ec_brick_consumable_size.py
  common/ops/support_ops/io_ops.py
  config/config.yml
  tests/functional/disperse/test_ec_brick_consumable_size.py
  tests/functional/disperse/test_ec_fops.py
Labels: testMigration

#1090 Migrate TC test_ec_file_rename_on_brick_down.py
  config/config.yml
  tests/functional/disperse/test_ec_file_rename_on_brick_down.py
Labels: testMigration

#1099 Migrate TC test_verify_permissions_on_root_dir_when_brick_down.py
  tests/functional/dht/test_verify_permissions_on_root_dir_when_brick_down.py
Labels: testMigration

#1107 Migrate TC test_stop_glusterd_while_rebalance_in_progress.py
  tests/functional/dht/test_stop_glusterd_while_rebalance_in_progress.py
Labels: testMigration

#1106 Common: Fix infinite recursion in case of reset-failed glusterd
  common/ops/gluster_ops/glusterd_ops.py
Labels: bug, Critical, Common

#1111 Migrate TC tests/functional/disperse/test_ec_eagerlock.py
  tests/functional/disperse/test_ec_eagerlock.py
Labels: testMigration

#1091 Migrate TC test_remove_brick_with_open_fd.py
  tests/functional/dht/test_remove_brick_with_open_fd.py
Labels: testMigration

#1097 Migrate TC test_verify_rebalance_with_locks_on_files.py
  tests/functional/dht/test_verify_rebalance_with_locks_on_files.py
Labels: testMigration

#1113 Migrate TC tests/functional/dht/test_time_taken_for_ls.py
  tests/functional/dht/test_time_taken_for_ls.py
Labels: testMigration

#1094 Migrate TC test_wipe_out_directory_permissions.py
  config/config.yml
  tests/functional/dht/test_wipe_out_directory_permissions.py
Labels: testMigration

#1112 Migrate TC tests/functional/dht/test_stack_overflow.py
  tests/functional/dht/test_stack_overflow.py
Labels: testMigration

#1117 Migrate TC test_sparse_file_creation_and_deletion.py
  tests/functional/dht/test_sparse_file_creation_and_deletion.py
Labels: testMigration

#1118 Migrate TC test_restart_glusterd_after_rebalance.py
  tests/functional/dht/test_restart_glusterd_after_rebalance.py
Labels: testMigration

#1119 Migrated TC test_rename_with_brick_min_free_limit_crossed.py
  tests/functional/dht/test_rename_with_brick_min_free_limit_crossed.py
Labels: testMigration

#1129 Migrate TC tests/functional/dht/test_rebalance_with_brick_down.py
  tests/functional/dht/test_rebalance_with_brick_down.py
Labels: testMigration

#1127 Migrate TC tests/functional/dht/test_rebalance_with_special_files.py
  tests/functional/dht/test_rebalance_with_special_files.py
Labels: testMigration

#1137 Migrated TC tests/functional/dht/test_rebalance_stop_mid_migration.py
  tests/functional/dht/test_rebalance_stop_mid_migration.py
Labels: testMigration

#1141 [Common] Update hostnames to IP in DHT Ops
  common/ops/gluster_ops/dht_ops.py
  common/ops/gluster_ops/volume_ops.py
Labels: Common

#1144 Migrate TC test_rebalance_with_acl_set_to_files.py
  common/ops/gluster_ops/mount_ops.py
  common/ops/support_ops/io_ops.py
  tests/functional/dht/test_rebalance_with_acl_set_to_files.py
Labels: testMigration
