Repository gluster/redant, pull requests merged in 2021-07, with the labels that each got.

#743 Modifying mount command
  common/ops/gluster_ops/mount_ops.py
Labels: enhancement

#747 Changing default config value for dist volume
  config/config.yml
Labels: enhancement

#750 [Result] Fixing skip count and time output
  core/result_handler.py
Labels: bug

#752 [Test] Custom setup invoked with decorator.
  tests/d_parent_test.py
  tests/functional/glusterd/test_get_state_on_brick_unmount.py
  tests/functional/glusterd/test_glusterd_quorum.py
  tests/functional/glusterd/test_mount_after_removing_client_logs_dir.py
  tests/functional/glusterd/test_peer_probe_firewall_ports_not_opened.py
  tests/functional/glusterd/test_replace_brick_quorum_not_met.py
  tests/functional/glusterd/test_setting_volume_option_when_one_node_is_down_in_cluster.py
  tests/functional/glusterd/test_volume_create_with_glusterd_restarts.py
  tests/functional/glusterd/test_volume_operations.py
Labels: enhancement

#740 Migrated test_impact_of_replace_brick_for_glustershd.py
  common/ops/gluster_ops/heal_ops.py
  tests/functional/arbiter/brick_cases/test_impact_of_replace_brick_for_glustershd.py
Labels: testMigration

#753 Migrated test_replacing_all_arbiter_bricks_in_the_volume.py
  tests/functional/arbiter/test_replacing_all_arbiter_bricks_in_the_volume.py
Labels: testMigration

#738 Migrated test_cyclic_brick_kill_list
  tests/functional/arbiter/brick_cases/test_cyclic_brick_kill_list.py
Labels: testMigration

#633 Migration of test_detach_node_used_to_mount.py
  common/ops/support_ops/io_ops.py
  tests/functional/glusterd/test_detach_node_used_to_mount.py
Labels: testMigration

#744 Migrated TC test_glusterd_statedump_with_server_client_quorum
  tests/functional/glusterd/test_glusterd_statedump_with_server_and_client_quorum_set.py
Labels: testMigration

#754 Updated the supported and tested distro detail
  README.md
Labels: documentation

#759 Fixed form_brick_cmd and replace_brick_from_volume
  common/ops/gluster_ops/brick_ops.py
  tests/example/sample_component/test_brick_ops.py
Labels: Common, bug

#763 [Common] FQDN to IP conv in vol status
  common/ops/gluster_ops/peer_ops.py
  common/ops/gluster_ops/volume_ops.py
  common/ops/support_ops/machine_ops.py
  tests/functional/glusterd/test_volume_reset.py
Labels: bug

#771 [TestFix] Changing glusterd.service path
  tests/functional/glusterd/test_enabling_glusterd_debug_mode.py
Labels: bug

#761 Migrate test_nuke_happy_path
  tests/functional/dht/test_nuke_happy_path.py
Labels: testMigration

#774 Added io ops
  common/ops/support_ops/io_ops.py
Labels: Common

#768 Added brick ops
  common/ops/gluster_ops/brick_ops.py
  common/ops/gluster_ops/volume_ops.py
  tests/example/sample_component/test_brick_ops.py
Labels: Common

#755 [Core][Common] Snap ops addition
  common/ops/gluster_ops/brick_ops.py
  common/ops/gluster_ops/snapshot_ops.py
  common/ops/gluster_ops/volume_ops.py
  common/ops/support_ops/machine_ops.py
  core/environ.py
  tests/d_parent_test.py
  tests/example/sample_component/test_snap_ops.py
  tests/functional/glusterd/test_change_reserve_limit.py
  tests/functional/glusterd/test_concurrent_set.py
  tests/functional/glusterd/test_create_vol_with_used_bricks.py
  tests/functional/glusterd/test_gluster_volume_status_xml_dump.py
  tests/functional/glusterd/test_glusterd_quorum.py
  tests/functional/glusterd/test_glusterd_statedump_with_server_and_client_quorum_set.py
  tests/functional/glusterd/test_peer_probe.py
  tests/functional/glusterd/test_profile_operations.py
  tests/functional/glusterd/test_profile_simultaneously_on_different_nodes.py
  tests/functional/glusterd/test_quorum_syslog.py
  tests/functional/glusterd/test_rebalance_hang.py
  tests/functional/glusterd/test_rebalance_new_node.py
  tests/functional/glusterd/test_volume_create.py
  tests/functional/glusterd/test_volume_operations.py
  tests/functional/glusterd/test_xml_dump_of_gluster_volume_status_during_rebalance.py
  tests/vol_destroy_test.py
Labels: Common, Core, documentation, enhancement

#780 Added heal ops
  common/ops/gluster_ops/heal_ops.py
  tests/example/sample_component/test_heal_ops.py
Labels: Common

#782 Added IO ops
  common/ops/support_ops/io_ops.py
Labels: Common

#783 Fix: Updated the function to use string instead of list
  common/ops/support_ops/io_ops.py
Labels: bug

#785 Used f strings in rmdir
  common/ops/support_ops/io_ops.py
Labels: Common

#786 Changing Upstream link
  CONTRIBUTING.md
Labels: documentation

#788 added io ops
  common/ops/support_ops/io_ops.py
  tests/example/sample_component/test_io.py
Labels: Common

#790 [Core] Result Handler improvement.
  README.md
  core/redant_main.py
  core/result_handler.py
  core/runner_thread.py
  core/test_runner.py
Labels: Core, enhancement

#793 Migrated test_afr_cli_no_splitbrain_resolution.py
  tests/functional/afr/test_afr_cli_no_splitbrain_resolution.py
Labels: testMigration

#791 Migrated test_afr_cli_gfid_splitbrain
  tests/functional/afr/test_afr_cli_gfid_splitbrain.py
Labels: testMigration

#798 Migrated test_file_permission_and_mode
  core/environ.py
  tests/functional/afr/test_file_permission_and_mode.py
Labels: testMigration

#800 Migrated test_gfid_assignment_on_dist_rep_vol.
  tests/functional/afr/test_gfid_assignment_on_dist_rep_vol.py
Labels: testMigration

#805 [TestMigration] Migration of activate/deactivate snap test.
  common/ops/gluster_ops/snapshot_ops.py
  tests/functional/snapshot/test_activate_deactivate.py
Labels: testMigration

#792 Migrated TC test_gfind_delete_file
  common/ops/support_ops/io_ops.py
  tests/functional/glusterfind/test_gfind_delete_file.py
Labels: testMigration

#808 [Common] Renaming gluster ops to glusterd ops.
  common/mixin.py
  common/ops/gluster_ops/glusterd_ops.py
  docs/BP/Ops/glusterd_ops.md
Labels: Common

#806 Migrated test_gfid_assignment_on_lookup
  tests/functional/afr/test_gfid_assignment_on_lookup.py
Labels: testMigration

#810 Migrated test_heal_command_unsuccessful_as_bricks_down
  tests/functional/afr/test_heal_command_unsuccessful_as_bricks_down.py
Labels: testMigration

#817 [Common] Glusterd ungraceful kill added.
  common/ops/gluster_ops/glusterd_ops.py
Labels: bug

#811 Migrated test_healed_and_heal_failed_command
  common/ops/gluster_ops/heal_ops.py
  tests/functional/afr/test_healed_and_heal_failed_command.py
Labels: testMigration

#816 Migrating snap auto delete test
  common/ops/gluster_ops/snapshot_ops.py
  tests/example/sample_component/test_snap_ops.py
  tests/functional/snapshot/test_auto_delete.py
Labels: testMigration

#818 Adding VSCode badge for repo
  README.md
Labels: enhancement

#824 [Core] Exception handling for constructor invocation.
  core/environ.py
  core/runner_thread.py
Labels: Core, Critical, bug

#823 Migrated test_heal_info_should_have_fixed_fields
  tests/functional/afr/test_heal_info_should_have_fixed_fields.py
Labels: testMigration

#830 Migrated test_client_side_quorum_with_fixed_validate_max_bricks
  tests/functional/afr/test_client_side_quorum_with_fixed_validate_max_bricks.py
Labels: testMigration

#825 Migrated test_readlink
  common/rexe.py
  core/environ.py
  tests/functional/afr/test_readlink.py
  tools/file_dir_ops.py
Labels: testMigration

#831 Migrated test_creating_deleting_files_reflect_available_space
  tests/functional/afr/test_creating_deleting_files_reflect_available_space.py
Labels: testMigration

#835 Migrated test_dir_time_stamp_restoration
  tests/functional/afr/heal/test_dir_time_stamp_restoration.py
  tests/vol_destroy_test.py
Labels: testMigration

#837 [TestMigration] Migration test_snap_invalid_names
  common/ops/gluster_ops/snapshot_ops.py
  tests/functional/snapshot/test_snap_invalid_names.py
Labels: testMigration

#836 Migrated test_shd_should_not_crash_executed_heal_info
  tests/functional/afr/test_shd_should_not_crash_executed_heal_info.py
Labels: testMigration

#842 [TestMigration] Migration of test_snap_glusterd_down
  tests/functional/snapshot/test_snap_glusterd_down.py
Labels: testMigration

#838 Migrated test_split_brain_with_hard_link
  tests/functional/afr/test_split_brain_with_hard_link_file.py
Labels: testMigration

#841 [TestMigration] Migrating test_snap_invlid_cases
  common/ops/gluster_ops/snapshot_ops.py
  tests/functional/snapshot/test_snap_invalid_cases.py
Labels: testMigration

#844 [TestMigration] Migrating test_snap_delete_snap_of_volume
  common/ops/gluster_ops/snapshot_ops.py
  tests/functional/snapshot/test_snap_delete_snap_of_volume.py
Labels: testMigration

#843 Migrated test_heal_info_while_accessing_file
  tests/functional/afr/heal/test_heal_info_while_accessing_file.py
Labels: testMigration

#850 Migrated test_gfid_heal
  tests/functional/afr/test_gfid_heal.py
Labels: testMigration

#852 Migrated test_existing_shd_should_take_care_of_self_healing
  tests/functional/afr/heal/test_existing_shd_should_take_care_of_self_healing.py
Labels: testMigration

#777 Migrate test_replica3_to_arbiter
  tests/functional/arbiter/brick_cases/test_replica3_to_arbiter.py
Labels: testMigration

#848 Migrate TC test_glusterd_snap_info_on_detached_node
  tests/functional/glusterd/test_glusterd_snap_info_on_detached_node.py
Labels: testMigration

#855 Migrated TC test_mount_point_while_deleting_files
  tests/functional/arbiter/test_mount_point_while_deleting_files.py
Labels: testMigration

#819 Migrated test_heal_fail_1x3
  tests/functional/afr/test_heal_fail_1x3.py
Labels: testMigration

#846 [Doc] Adding Snap ops markdown
  common/ops/gluster_ops/snapshot_ops.py
  docs/BP/Ops/README.md
  docs/BP/Ops/snap_ops.md
Labels: documentation

#847 [Doc] Adding environ method details.
  core/environ.py
  docs/BP/Core/README.md
  docs/BP/Core/environ.md
  docs/BPIndex.md
Labels: documentation

#856 Migrated test_data_self_heal_algorithm_full_default
  common/ops/support_ops/io_ops.py
  tests/functional/arbiter/test_data_self_heal_algorithm_full_default.py
Labels: testMigration

#857 Migrated test_gfid_self_heal
  tests/functional/arbiter/test_gfid_self_heal.py
Labels: testMigration

#551 Migration of test_volume_network_ping_timeout.py
  tests/functional/glusterd/test_volume_network_ping_timeout.py
Labels: testMigration

#865 [Core][Common] Adding snap mount
  common/ops/gluster_ops/mount_ops.py
  common/ops/gluster_ops/snapshot_ops.py
  common/ops/gluster_ops/volume_ops.py
  core/environ.py
  tests/example/sample_component/test_snap_ops.py
Labels: Common, Core, enhancement

#877 Fixing typo in config
  config/config.yml
Labels: bug

#858 Migrated test_metadata_self_heal_on_open_fd
  common/ops/support_ops/io_ops.py
  tests/functional/arbiter/test_create_snapshot_and_verify_content.py
  tests/functional/arbiter/test_metadata_self_heal_on_open_fd.py
  tests/functional/glusterd/test_volume_network_ping_timeout.py
Labels: testMigration

#882 [Common] Adding view_snap_from_mount method
  common/ops/gluster_ops/mount_ops.py
  docs/BP/Ops/mount_ops.md
  tests/example/sample_component/test_snap_ops.py
Labels: Common

#885 Added arequal-checksum install script
  core/environ.py
  tools/arequal_install.sh
Labels: enhancement

#886 [Core] Handling standalone exclude output
  core/result_handler.py
Labels: bug

#881 Migrated test_data_self_heal_daemon_off
  tests/functional/arbiter/test_data_self_heal_daemon_off.py
Labels: testMigration

#832 Migrated test_replica_eager_lock
  tests/functional/afr/test_replica_eager_lock.py
Labels: testMigration

#895 [Common] Snap stray lv removal
  common/ops/gluster_ops/volume_ops.py
  common/ops/support_ops/machine_ops.py
  docs/BP/Ops/machine_ops.md
  docs/BP/Ops/volume_ops.md
  tests/d_parent_test.py
  tests/functional/glusterd/test_change_reserve_limit.py
  tests/functional/glusterd/test_concurrent_set.py
  tests/functional/glusterd/test_create_vol_with_used_bricks.py
  tests/functional/glusterd/test_gluster_volume_status_xml_dump.py
  tests/functional/glusterd/test_glusterd_statedump_with_server_and_client_quorum_set.py
  tests/functional/glusterd/test_peer_probe.py
  tests/functional/glusterd/test_profile_operations.py
  tests/functional/glusterd/test_profile_simultaneously_on_different_nodes.py
  tests/functional/glusterd/test_quorum_syslog.py
  tests/functional/glusterd/test_volume_create.py
  tests/functional/glusterd/test_volume_operations.py
  tests/vol_destroy_test.py
  tools/linting.sh
Labels: Common, bug

#899 [Core] Exclude test path check
  core/parsing/params_handler.py
  core/redant_main.py
Labels: Core, bug

#905 Modified maintainers file
  MAINTAINERS
Labels: documentation

#889 Migrted test_handling_data_split_brain_of_files_heal_command
  tests/functional/arbiter/test_handling_data_split_brain_of_files_heal_command.py
Labels: testMigration
