Repository gluster/redant, pull requests merged in 2021-06, with the labels that each got.

#545 [Config] Tests added to config.yml
  config/config.yml
Labels: bug

#537 Migrated test_volume_get
  common/ops/gluster_ops/gluster_ops.py
  common/ops/gluster_ops/volume_ops.py
  tests/functional/glusterd/test_volume_get.py
Labels: testMigration

#302 Added test_create_vol_with_used_bricks
  tests/functional/glusterd/test_create_vol_with_used_bricks.py
Labels: enhancement

#565 Update volume_ops.py
  common/ops/gluster_ops/volume_ops.py
Labels: bug

#566 Changing traceback fn call
  tests/functional/glusterd/test_volume_set_with_quorum_enabled.py
Labels: bug

#567 [Test] Making reset optional
  tests/d_parent_test.py
Labels: bug

#561 Migration of test_peer_status
  tests/functional/glusterd/test_peer_status.py
Labels: testMigration

#570 Volume reset for cluster level options.
  core/environ.py
  tests/d_parent_test.py
Labels: bug

#572 Update Add brick with force option
  common/ops/gluster_ops/brick_ops.py
Labels: bug

#571 MIssing items in dict iterations
  tests/d_parent_test.py
Labels: bug

#579 [Testfix] Changing the key value
  tests/functional/glusterd/test_rebalance_when_quorum_not_met.py
Labels: Test, bug

#564 Migrated test_enable_brickmux_create_and_stop_three_volumes
  tests/functional/glusterd/test_enable_brickmux_create_and_stop_three_volumes.py
Labels: testMigration

#578 Migrated test_profile_operations_with_one_node_down
  tests/example/sample_component/test_profile_ops.py
  tests/functional/glusterd/test_profile_operations_with_one_node_down.py
Labels: testMigration

#591 Migration of test_restart_glusterd_while_rebalancing.py
  common/ops/gluster_ops/brick_ops.py
  tests/functional/glusterd/test_restart_glusterd_while_rebalancing.py
Labels: testMigration

#594 Modified test_gluster_vol_status_xml_dump
  tests/functional/glusterd/test_gluster_volume_status_xml_dump.py
Labels: Test

#590 Migrated test_add_brick
  common/ops/gluster_ops/brick_ops.py
  tests/functional/glusterd/test_add_brick.py
Labels: testMigration

#597 Migrating test_reserve_limt_change_while_rebalance.py
  tests/functional/glusterd/test_reserve_limt_change_while_rebalance.py
Labels: testMigration

#458 Migrated test_reserved_port_range_for_gluster
  tests/functional/glusterd/test_reserved_port_range_for_gluster.py
Labels: limitations, testMigration

#602 [TestFix] Fixing test_probe_hostname
  config/config.yml
  tests/functional/glusterd/test_probe_hostname.py
Labels: bug

#606 Adding Flags as cli output
  README.md
Labels: documentation

#603 Migrate test_volume_create_with_glusterd_restarts
  tests/functional/glusterd/test_volume_create_with_glusterd_restarts.py
Labels: testMigration

#466 Migration of test_volume_status_with_absent_bricks
  common/ops/gluster_ops/volume_ops.py
  tests/functional/glusterd/test_volume_status_with_absent_bricks.py
Labels: testMigration

#611 Fixed condition in test_volume_status_with_absent_bricks
  tests/functional/glusterd/test_volume_status_with_absent_bricks.py
Labels: testMigration

#563 [Test] Migrate test_volume_reduce_replica.py
  common/ops/gluster_ops/volume_ops.py
  config/config.yml
  tests/functional/glusterd/test_volume_reduce_replica.py
Labels: testMigration

#607 Migrated test_mountpoint_ownership_post_volume_restart
  common/ops/support_ops/io_ops.py
  tests/functional/glusterd/test_mountpoint_ownership_post_volume_restart.py
Labels: testMigration

#618 [Core] Simplifying the Worker job handling
  core/test_runner.py
Labels: Core, enhancement

#620 [Test] Migration of a glusto TC
  tests/functional/glusterd/test_remove_brick_after_restart_glusterd.py
Labels: testMigration

#613 Migration of test_bricks_online_after_node_reboot.py
  tests/functional/glusterd/test_bricks_online_after_node_reboot.py
Labels: testMigration

#621 Fixed mountpoint connection failure in test
  common/ops/gluster_ops/mount_ops.py
  tests/functional/glusterd/test_mountpoint_ownership_post_volume_restart.py
Labels: bug

#604 Migrating test_add_identical_brick_new_node.py
  tests/functional/glusterd/test_add_identical_brick_new_node.py
Labels: testMigration

#623 [Common][TestM] Ops and Test migration
  common/ops/gluster_ops/volume_ops.py
  tests/example/sample_component/test_vol_ops.py
Labels: Common, enhancement

#632 [Core][Test] Cleanup fix
  common/ops/support_ops/machine_ops.py
  tests/d_parent_test.py
Labels: bug

#630 Migration of test_status_string_in_volstatus.py
  tests/functional/glusterd/test_status_string_in_volstatus.py
Labels: testMigration

#327 Migration of test_gluster_detect_drop_of_outbound_traffic.py
  tests/functional/glusterd/test_gluster_detect_drop_of_outbound_traffic.py
Labels: testMigration

#557 Migrated test_setting_volume_option_when_one_node_is_down_in_cluster
  tests/functional/glusterd/test_setting_volume_option_when_one_node_is_down_in_cluster.py
Labels: testMigration

#634 Main readme updation
  README.md
Labels: documentation

#636 [Common] Correcting function invocation name
  common/ops/support_ops/machine_ops.py
Labels: bug

#354 Migration of test_setting_volume_option_with_more_than_4096_characters
  tests/functional/glusterd/test_setting_volume_option_with_more_than_4096_characters.py
Labels: testMigration

#627 Migrated test_probe_glusterd_down
  common/ops/support_ops/machine_ops.py
  tests/functional/glusterd/test_probe_glusterd_down.py
Labels: testMigration

#583 Migration of test_volume_create.py
  tests/functional/glusterd/test_volume_create.py
Labels: testMigration

#637 Migrated test_peer_detach_check_warning_message
  common/ops/gluster_ops/peer_ops.py
  common/rexe.py
  tests/functional/glusterd/test_peer_detach_check_warning_message.py
Labels: testMigration

#641 Changing conditional bash from and
  common/ops/support_ops/machine_ops.py
Labels: bug

#643 Added documentation for volume ops
  docs/BP/Ops/volume_ops.md
Labels: documentation

#645 Added documentation for peer ops
  common/ops/gluster_ops/peer_ops.py
  docs/BP/Ops/peer_ops.md
Labels: documentation

#655 Added documentation for rebalance ops
  docs/BP/Ops/rebalance_ops.md
Labels: documentation

#653 Added documentation for profile_ops
  docs/BP/Ops/profile_ops.md
Labels: documentation

#651 Added docs for brick ops
  docs/BP/Ops/brick_ops.md
Labels: documentation

#650 Added doc for machine ops
  common/ops/support_ops/machine_ops.py
  docs/BP/Ops/machine_ops.md
Labels: documentation

#657 Added documentation for heal ops
  docs/BP/Ops/README.md
  docs/BP/Ops/heal_ops.md
Labels: documentation

#659 Added mount ops documentation
  common/ops/gluster_ops/mount_ops.py
  docs/BP/Ops/mount_ops.md
Labels: documentation

#661 Added shared_storage_ops documentation
  docs/BP/Ops/shared_storage_ops.md
Labels: documentation

#663 Added documentation for newly added function in glsuter ops
  docs/BP/Ops/glusterd_ops.md
Labels: documentation

#664 Migrated test_enabling_glusterd_debug_mode
  common/ops/support_ops/io_ops.py
  common/ops/support_ops/machine_ops.py
  tests/functional/glusterd/test_enabling_glusterd_debug_mode.py
Labels: testMigration

#666 Removed sp flag
  README.md
  core/redant_main.py
Labels: Core

#671 Added bulk_volume_creation function
  common/ops/gluster_ops/volume_ops.py
  tests/example/sample_component/test_vol_ops.py
Labels: Common

#673 Remoeved hardcoded force values
  common/ops/gluster_ops/brick_ops.py
  common/ops/gluster_ops/volume_ops.py
Labels: Common

#677 Added more volume ops
  common/ops/gluster_ops/volume_ops.py
  tests/example/sample_component/test_vol_ops.py
  tests/functional/glusterd/test_gluster_detect_drop_of_outbound_traffic.py
  tests/functional/glusterd/test_volume_status_with_absent_bricks.py
Labels: Common

#681 Added more functions in brick ops
  common/ops/gluster_ops/brick_ops.py
Labels: Common

#690 Migrated test_data_delete
  tests/functional/arbiter/test_data_delete.py
Labels: testMigration

#683 Added auth ops
  common/mixin.py
  common/ops/gluster_ops/auth_ops.py
  tests/example/sample_component/test_vol_ops.py
Labels: Common

#684 Test: Added a TC for line coverage
  common/mixin.py
  common/ops/gluster_ops/bitrot_ops.py
  tests/functional/glusterd/test_volume_features_for_line_coverage.py
Labels: enhancement

#692 Added heal ops
  common/ops/gluster_ops/heal_ops.py
  tests/example/sample_component/test_heal_ops.py
Labels: Common

#688 Migrated test_glusterd_memory_consumption_increase
  common/ops/gluster_ops/gluster_ops.py
  config/config.yml
  tests/functional/glusterd/test_glusterd_memory_consumption_increase.py
Labels: testMigration

#695 Added functions related to user
  common/ops/support_ops/io_ops.py
  tests/example/sample_component/test_user_ops.py
Labels: Common

#686 Migrated test_brickmux_brick_process
  common/ops/gluster_ops/volume_ops.py
  common/ops/support_ops/machine_ops.py
  tests/functional/glusterd/test_brickmux_brick_process.py
Labels: Common, testMigration

#705 Migrated test_no_data_loss_arbiter_vol_after_rename_file
  common/ops/support_ops/io_ops.py
  tests/functional/arbiter/test_no_data_loss_arbiter_vol_after_rename_file.py
Labels: testMigration

#668 Migrated test_remove_brick_scenarios
  common/ops/gluster_ops/brick_ops.py
  tests/functional/glusterd/test_remove_brick_scenarios.py
Labels: testMigration

#702 Added daemon related functions in heal ops
  common/ops/gluster_ops/heal_ops.py
  tests/example/sample_component/test_heal_ops.py
Labels: Common

#708 Migrated test_oom_on_client_heal_is_in_progress_arbiter
  common/ops/support_ops/io_ops.py
  tests/functional/arbiter/test_oom_on_client_heal_is_in_progress_arbiter.py
Labels: testMigration

#713 [Common] Fix bulk volume create
  common/ops/gluster_ops/volume_ops.py
  tests/functional/glusterd/test_brickmux_brick_process.py
  tests/functional/glusterd/test_glusterd_memory_consumption_increase.py
Labels: bug

#710 Migrated test_resolving_meta_data_split_brain_extended_attributes.py
  common/ops/gluster_ops/heal_ops.py
  tests/functional/arbiter/test_resolving_meta_data_split_brain_extended_attributes.py
Labels: testMigration

#714 Migrated test_split_brain
  tests/functional/arbiter/test_split_brain.py
Labels: testMigration

#717 [Core][Test] Skip conditional in test
  core/result_handler.py
  core/runner_thread.py
  core/test_runner.py
  tests/d_parent_test.py
  tests/functional/glusterd/test_create_vol_with_used_bricks.py
  tests/functional/glusterd/test_gluster_does_not_do_posix_lock_when_multiple_client.py
  tests/functional/glusterd/test_glusterd_quorum.py
  tests/functional/glusterd/test_glusterd_split_brain.py
  tests/functional/glusterd/test_volume_create.py
  tests/functional/glusterd/test_volume_create_with_glusterd_restarts.py
  tests/functional/glusterd/test_volume_status_show_bricks_online_though_brickpath_deleted.py
  tests/nd_parent_test.py
Labels: Core, Test, enhancement

#722 [Doc] Doc refactoring and supported os info
  README.md
  docs/BP/Ops/peer_ops.md
  docs/RP/Core/result_handler.md
  tests/README.md
Labels: bug, documentation, enhancement

#720 [Core] Reformatting time format in output
  core/result_handler.py
Labels: enhancement

#726 [Core][Test] Removal of conv_dict
  config/config.yml
  core/parsing/params_handler.py
  docs/BP/Ops/volume_ops.md
  tests/d_parent_test.py
  tests/example/sample_component/test_vol_ops.py
  tests/functional/glusterd/test_add_brick.py
  tests/functional/glusterd/test_add_identical_brick_new_node.py
  tests/functional/glusterd/test_brickmux_brick_process.py
  tests/functional/glusterd/test_bricks_online_after_node_reboot.py
  tests/functional/glusterd/test_change_reserve_limit.py
  tests/functional/glusterd/test_concurrent_set.py
  tests/functional/glusterd/test_create_vol_with_used_bricks.py
  tests/functional/glusterd/test_enable_brickmux_create_and_stop_three_volumes.py
  tests/functional/glusterd/test_get_state_on_brick_unmount.py
  tests/functional/glusterd/test_gluster_volume_status_xml_dump.py
  tests/functional/glusterd/test_glusterd_memory_consumption_increase.py
  tests/functional/glusterd/test_glusterd_quorum.py
  tests/functional/glusterd/test_mount_after_removing_client_logs_dir.py
  tests/functional/glusterd/test_peer_detach.py
  tests/functional/glusterd/test_peer_probe.py
  tests/functional/glusterd/test_peer_status.py
  tests/functional/glusterd/test_probe_hostname.py
  tests/functional/glusterd/test_profile_operations.py
  tests/functional/glusterd/test_profile_simultaneously_on_different_nodes.py
  tests/functional/glusterd/test_quorum_syslog.py
  tests/functional/glusterd/test_rebalance_hang.py
  tests/functional/glusterd/test_rebalance_new_node.py
  tests/functional/glusterd/test_replace_brick_quorum_not_met.py
  tests/functional/glusterd/test_reserved_port_range_for_gluster.py
  tests/functional/glusterd/test_setting_volume_option_when_one_node_is_down_in_cluster.py
  tests/functional/glusterd/test_volume_create.py
  tests/functional/glusterd/test_volume_create_with_glusterd_restarts.py
  tests/functional/glusterd/test_volume_operations.py
  tests/functional/glusterd/test_volume_status_xml.py
  tests/functional/glusterd/test_xml_dump_of_gluster_volume_status_during_rebalance.py
  tests/lazy_parent_test.py
  tests/nd_parent_test.py
  tests/vol_create_test.py
Labels: bug, enhancement

#731 [Core] XLS exception handling
  core/result_handler.py
Labels: bug

#724 Migrated test_afr_read_write
  common/ops/gluster_ops/volume_ops.py
  tests/d_parent_test.py
  tests/functional/arbiter/test_afr_read_write.py
Labels: testMigration

#729 Added heal ops required for arbiter
  common/ops/gluster_ops/heal_ops.py
  tests/example/sample_component/test_heal_ops.py
Labels: Common

#737 Gitignore adding vscode
  .gitignore
Labels: enhancement

#733 [Core] Sanitize enhancement for change in volume brick counts
  common/ops/gluster_ops/brick_ops.py
  common/ops/gluster_ops/volume_ops.py
  core/environ.py
  tests/example/sample_component/test_brick_ops.py
Labels: Core, enhancement
