Repository gluster/redant, pull requests merged in 2021-08, with the labels that each got.

#910 [Doc] Adding Known issues
  README.md
  docs/BPIndex.md
  docs/README.md
  docs/RP/HLD.md
  docs/RPIndex.md
  docs/known_issues.md
Labels: documentation

#916 [Core][Common][Test] Exclude list fix
  common/ops/support_ops/machine_ops.py
  config/config.yml
  core/result_handler.py
  tests/functional/glusterd/test_detach_node_used_to_mount.py
  tests/functional/glusterd/test_quorum_syslog.py
Labels: Test

#920 [Common] Clearing out files and dirs
  common/ops/support_ops/machine_ops.py
Labels: enhancement

#928 [Common] Snap clone environ changes
  common/ops/gluster_ops/snapshot_ops.py
  tests/example/sample_component/test_snap_ops.py
Labels: bug, Common

#933 [Core] Increased debug log penetration.
  core/environ.py
  core/redant_main.py
  core/result_handler.py
Labels: Core

#935 [Core] Fixing logger obj call
  core/redant_main.py
Labels: bug, Urgent

#930 [Doc] Deciding test nature markdown added
  docs/BP/TestNature.md
  docs/BPIndex.md
Labels: documentation

#931 [Tool] Log access flask server
  requirements.txt
  tools/README.md
  tools/log_server/README.md
  tools/log_server/log_access.ini
  tools/log_server/log_access.py
  tools/log_server/log_access.sh
Labels: enhancement, Tools

#939 [Core] Fixing argument order
  core/redant_main.py
Labels: bug, Core

#943 [Core] Exception handling improvement
  core/redant_main.py
  docs/BP/CatchAllException.md
  docs/BPIndex.md
  tests/d_parent_test.py
  tests/nd_parent_test.py
Labels: bug, documentation, Core

#941 [Common] Preventing ssh hang in command execution
  common/rexe.py
Labels: bug, Common

#944 [Tool] Linting behavior similar to GH Actions
  CONTRIBUTING.md
  tools/README.md
  tools/linting.sh
Labels: enhancement

#949 [Config] Adding a skip test
  config/config.yml
Labels: bug

#845 [TestMigration] Migration of test_validate_snap_del_gd_down
  tests/functional/snapshot/test_validate_snap_del_gd_down.py
Labels: testMigration

#951 [testMigration] Migrating test_uss_brick_down.py
  common/ops/gluster_ops/brick_ops.py
  core/runner_thread.py
  tests/functional/snapshot/test_uss_brick_down.py
  tools/linting.sh
Labels: testMigration

#952 Migrated TC tests/functional/afr/heal/test_data_split_brain_resolution.py
  tests/functional/afr/heal/test_data_split_brain_resolution.py
Labels: testMigration

#953 Migrated TC tests/functional/afr/heal/test_heal_info_no_hang.py
  tests/functional/afr/heal/test_heal_info_no_hang.py
Labels: testMigration

#954 [Test] Migrating test_activate_on_create
  tests/functional/snapshot/test_activate_on_create.py
Labels: testMigration

#956 [Test] Migrating test_snap_clone_from_snap.py
  tests/functional/snapshot/test_snap_clone_from_snap.py
Labels: testMigration

#957 [Test] Migrating test_snap_info.py
  tests/functional/snapshot/test_snap_info.py
Labels: testMigration

#960 [Test] Migration test_snapshot_create.py
  config/config.yml
  tests/functional/snapshot/test_snapshot_create.py
Labels: testMigration

#966 Docs: Updated the docs structure
  docs/BP/Tools/README.md
  docs/BPIndex.md
  docs/CatchAllException.md
  docs/Code_Considerations.md
  docs/Common/README.md
  docs/Common/logging.md
  docs/Common/mixin.md
  docs/Common/rexe.md
  docs/Common/volds.md
  docs/Core/README.md
  docs/Core/environ.md
  docs/Core/result_handler.md
  docs/HLD.md
  docs/Ops/README.md
  docs/Ops/brick_ops.md
  docs/Ops/glusterd_ops.md
  docs/Ops/heal_ops.md
  docs/Ops/io_ops.md
  docs/Ops/machine_ops.md
  docs/Ops/mount_ops.md
  docs/Ops/peer_ops.md
  docs/Ops/profile_ops.md
  docs/Ops/rebalance_ops.md
  docs/Ops/rexe.md
  docs/Ops/shared_storage_ops.md
  docs/Ops/snap_ops.md
  docs/Ops/volume_ops.md
  docs/README.md
  docs/RP/Common/README.md
  docs/RP/Core/README.md
  docs/RP/Test/README.md
  docs/RP/Tools/migrate_tc.md
  docs/RPIndex.md
  docs/TestNature.md
  docs/Tools/README.md
  docs/Tools/glusto_redant_parser.md
  docs/Tools/migratingTC.md
  docs/WIRA.md
Labels: documentation

#965 [Test] Migrating test_snap_list_after_restart.py
  tests/functional/snapshot/test_snap_list_after_restart.py
Labels: testMigration

#964 [Test] Migrating test_snap_uss_while_io.py
  tests/functional/snapshot/test_snap_uss_while_io.py
Labels: testMigration

#962 Migrated TC tests/functional/afr/heal/test_metadata_split_brain_resolution.py
  common/ops/support_ops/io_ops.py
  tests/functional/afr/heal/test_metadata_split_brain_resolution.py
Labels: testMigration

#971 Migrated TC tests/functional/afr/heal/test_no_glustershd_with_distribute.py
  tests/functional/afr/heal/test_no_glustershd_with_distribute.py
Labels: testMigration

#972 Remove stripCount variable from volume options
  common/ops/gluster_ops/volume_ops.py
Labels: Common

#970 Migrated TC test_client_side_quorum_with_cross2
  common/ops/support_ops/io_ops.py
  config/config.yml
  tests/functional/afr/test_client_side_quorum_fixed_with_cross2.py
  tests/functional/afr/test_client_side_quorum_with_cross2.py
Labels: testMigration

#976 Migrated TC test_impact_of_replace_brick_on_glustershd.py
  tests/functional/afr/heal/test_impact_of_replace_brick_on_glustershd.py
Labels: testMigration

#979 Migrated TC test_server_side_healing_happens_only_when_glustershd_running.py
  tests/functional/afr/heal/test_server_side_healing_happens_only_when_glustershd_running.py
Labels: testMigration

#985 Migrated TC test_self_heal_with_meta_data_entry_and_files_removed.py
  tests/functional/afr/heal/test_self_heal_with_meta_data_entry_and_files_removed.py
Labels: testMigration

#986 Migrated TC test_self_heal_with_link_files.py
  tests/functional/afr/heal/test_self_heal_with_link_files.py
Labels: testMigration

#992 Migrated TC test_self_heal_daemon_process.py
  config/config.yml
  tests/functional/afr/heal/test_self_heal_daemon_process.py
Labels: testMigration

#794 Migrated test_dir_gfid_heal_on_all_subvols.py
  common/ops/support_ops/io_ops.py
  tests/functional/afr/test_dir_gfid_heal_on_all_subvols.py
Labels: testMigration

#995 [Core] Changing default dirs
  README.md
  common/ops/gluster_ops/dht_ops.py
  common/ops/support_ops/io_ops.py
  core/environ.py
  core/redant_main.py
  docs/catch_all_exception.md
  tests/functional/afr/test_afr_with_snapshot.py
  tests/functional/afr/test_afr_with_snapshot_delete.py
  tests/functional/afr/test_afr_with_snapshot_rename.py
  tests/functional/afr/test_arb_to_repl_conversion_with_io.py
  tests/functional/afr/test_client_side_quorum_fixed_with_cross2.py
  tests/functional/afr/test_client_side_quorum_with_auto_option.py
  tests/functional/afr/test_client_side_quorum_with_auto_option_overwrite_fixed.py
  tests/functional/afr/test_client_side_quorum_with_cross2.py
  tests/functional/afr/test_client_side_quorum_with_fixed_for_cross3.py
  tests/functional/afr/test_client_side_quorum_with_multiple_volumes.py
  tests/functional/afr/test_metadata_self_heal_client_side_heal.py
  tests/functional/afr/test_multiple_clients_dd_on_same_file_default.py
  tests/functional/afr/test_replace_brick_self_heal_io_in_progress.py
  tests/functional/afr/test_volume_set_options.py
  tests/functional/arbiter/test_data_self_heal_algorithm_diff_default.py
  tests/functional/arbiter/test_data_self_heal_algorithm_diff_heal_command.py
  tests/functional/arbiter/test_entry_self_heal_heal_command.py
  tests/functional/arbiter/test_handling_data_split_brain_of_files_heal_command.py
  tools/log_server/log_access.ini
  tools/log_server/log_access.py
Labels: bug, Core

#1005 [Common] Fixing script invocation path
  common/ops/support_ops/io_ops.py
Labels: bug, Common

#1003 [Test] Bringing custom terminate under t-e block
  tests/functional/arbiter/test_metadata_self_heal_on_open_fd.py
Labels: bug
