Repository gluster/redant, pull requests merged in 2021-04, with the labels that each got.

#151 Enhancing the config file
  config/CONFIG_README.md
  config/config.yml
Labels: enhancement

#155 Volume Ops and test case added
  core/__init__.py
  support/__init__.py
  support/ops/gluster_ops/volume_ops.py
  tests/functional/glusterd/test_volume_list_options.py
Labels: enhancement

#157 Comparision test_case added and unmount volume in VolumeOps
  support/ops/gluster_ops/volume_ops.py
  tests/functional/glusterd/test_comparision.py
Labels: enhancement

#158 Hostname is added to config
  config/config.yml
  core/parsing/params_handler.py
Labels: enhancement

#165 Handle non volume TCs.
  core/test_list_builder.py
Labels: bug, enhancement

#164 Gluster-ops enhancement
  support/ops/gluster_ops/gluster_ops.py
  tests/functional/glusterd/test_glusterd_start_stop.py
Labels: bug, enhancement

#141 Functionalities are added in ops lib
  support/ops/gluster_ops/peer_ops.py
  support/ops/support_ops/io_ops.py
  tests/example/test_comparison.py
  tests/example/test_comparison2.py
  tests/example/test_file_creation.py
Labels: enhancement

#168 Logger doesn't reflect proper module and line number
  support/ops/gluster_ops/gluster_ops.py
  support/ops/gluster_ops/peer_ops.py
  support/ops/gluster_ops/volume_ops.py
  support/ops/support_ops/io_ops.py
  support/ops/support_ops/relog.py
  support/ops/support_ops/rexe.py
Labels: bug

#170 [Testfix] Test failing with erraneous function calls.
  support/ops/support_ops/rexe.py
  tests/functional/glusterd/test_peer_probe_detach.py
  tests/functional/glusterd/test_volume_create_delete.py
Labels: bug

#175 Script for cleaning caache files in python
  README.md
  tools/clean_pycache
Labels: enhancement

#176 Config File Enhancement
  config/CONFIG_README.md
  config/config.yml
  core/parsing/params_handler.py
  core/runner_thread.py
  support/ops/support_ops/rexe.py
  tests/parent_test.py
Labels: enhancement

#160 Cluster creation funtionality added
  support/ops/gluster_ops/peer_ops.py
  tests/functional/glusterd/test_peer_probe_detach.py
Labels: enhancement

#178 Fixing rexe and relog ops
  README.md
  core/redant_main.py
  support/logging.md
  support/mixin.py
  support/relog.py
  support/rexe.py
Labels: bug, enhancement

#180 Parent test now an abstract parent test
  core/runner_thread.py
  support/ops/gluster_ops/peer_ops.py
  tests/example/sample_component/test_file_creation.py
  tests/example/sample_component/test_sample.py
  tests/functional/glusterd/test_glusterd_start_stop.py
  tests/functional/glusterd/test_peer_probe_detach.py
  tests/functional/glusterd/test_volume_create_delete.py
  tests/functional/glusterd/test_volume_list_options.py
  tests/parent_test.py
Labels: enhancement

#187 Modified the logging for specific tests and runs
  support/relog.py
  tests/parent_test.py
Labels: documentation, enhancement

#189 Added the code to handle the error in case of rebooting the node
  support/rexe.py
Labels: bug

#190 [Lib] Adding terminate in Rexe.
  support/rexe.py
  tests/parent_test.py
Labels: bug

#183 Modified the peer ops file
  support/ops/gluster_ops/peer_ops.py
Labels: enhancement

#197 Log dir structure is enhanced
  core/test_runner.py
  support/relog.py
Labels: enhancement

#194 Passing the config hashmap to the parent test.
  core/parsing/params_handler.py
  core/redant_main.py
  core/runner_thread.py
  core/test_runner.py
  tests/parent_test.py
Labels: enhancement

#200 Standardized the code
  support/mixin.py
  support/ops/gluster_ops/gluster_ops.py
  support/ops/gluster_ops/peer_ops.py
  support/ops/gluster_ops/volume_ops.py
  support/ops/support_ops/io_ops.py
  support/relog.py
  support/rexe.py
  tests/example/sample_component/test_sample.py
  tests/functional/glusterd/test_peer_probe_detach.py
  tests/functional/glusterd/test_volume_create_delete.py
Labels: documentation, enhancement

#192 Added linting script
  CONTRIBUTING.md
  __init__.py
  support/ops/__init__.py
  support/ops/gluster_ops/__init__.py
  support/ops/support_ops/__init__.py
  tests/example/__init__.py
  tests/example/sample_component/__init__.py
  tests/functional/__init__.py
  tests/functional/glusterd/__init__.py
  tools/README.md
  tools/linting.sh
Labels: enhancement

#201 [Lib] Adding random execution handling in Rexe.
  core/parsing/params_handler.py
  core/redant_main.py
  core/result_handler.py
  core/runner_thread.py
  core/test_list_builder.py
  requirements.txt
  support/ops/gluster_ops/gluster_ops.py
  support/ops/gluster_ops/peer_ops.py
  support/ops/gluster_ops/volume_ops.py
  support/ops/support_ops/io_ops.py
  support/relog.py
  support/rexe.py
  tests/example/sample_component/test_file_creation.py
  tests/example/sample_component/test_sample.py
  tests/functional/glusterd/test_glusterd_start_stop.py
  tests/functional/glusterd/test_peer_probe_detach.py
  tests/functional/glusterd/test_volume_create_delete.py
  tests/parent_test.py
Labels: enhancement

#202 Ops Readme has been added
  config/CONFIG_README.md
  support/ops/OPS_README.md
Labels: enhancement

#199 Added procedure to write a test case
  tests/README.md
Labels: documentation, enhancement

#205 Fixing cluster creation and cluster deletion fn
  support/ops/gluster_ops/peer_ops.py
  support/relog.py
  support/rexe.py
  tests/functional/glusterd/test_peer_probe_detach.py
  tests/functional/glusterd/test_volume_create_delete.py
  tests/parent_test.py
Labels: enhancement

#191 Abstract Ops is added
  support/ops/abstract_ops.py
  support/ops/gluster_ops/gluster_ops.py
  support/ops/gluster_ops/peer_ops.py
  support/ops/gluster_ops/volume_ops.py
  support/ops/support_ops/io_ops.py
  tests/example/sample_component/test_file_creation.py
  tests/example/sample_component/test_sample.py
Labels: enhancement

#218 Modified the link in the readme
  tests/README.md
Labels: documentation

#224 Volume creation in parent test and param handler changes
  common/ops/abstract_ops.py
  common/ops/gluster_ops/volume_ops.py
  core/environ.py
  core/parsing/params_handler.py
  core/redant_main.py
  core/runner_thread.py
  core/test_runner.py
  tests/example/sample_component/test_file_creation.py
  tests/example/sample_component/test_sample.py
  tests/example/sample_component/test_vol_creation.py
  tests/parent_test.py
Labels: Critical, enhancement

#230 Converting threading to multiprocessing
  core/redant_main.py
  core/result_handler.py
  core/test_runner.py
Labels: Critical, documentation, enhancement

#233 Added the passwordless ssh code in rexe
  common/rexe.py
Labels: enhancement
